### ISSUE TITLE
xml annotation has initial sourcefile rather than tile filename, which causes problems when converting to TF records

### ISSUE THREAD

**Issue by JJmistry** [acl21/image_bbox_slicer#11] opened 2021-06-29 18:24 UTC
Hi,

This is a fab tool but unfortunately, it places the source filename in the XML not the tile filename

    <filename>**ORIGINAL_FILENAME_WITHOUT_FILETYPE**</filename>
    <path>**ORIGINAL_FILEPATH_WITHOUT_FILETYPE**</path>
    <source>

When using the scripts from the Tensorflow object detection API tutorial, this causes creation of TF records to fail as it looks for files, which arent there
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#preparing-the-dataset

I will work on a PR to address it but wanted to raise this as an issue

**Comment by acl21** [comment] 2021-06-29 19:15
Hi, 

Firstly, I am unable to reproduce this. For me, I get the tile filename correctly in the XML. But I noticed something that could be causing this issue - the path is completely wrong. I now fixed it and just pushed the code. 

Please use the latest version, it should solve your issue.

**Closed as completed** 2021-06-30 05:13 UTC

**Comment by acl21** [comment] 2021-06-30 05:14
Please reopen the issue if the changes don't help.
